import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Button, Heading, HStack, Image, Stack, Text } from '@chakra-ui/react'
import { Icon } from '@chakra-ui/react'
import { HiCheckCircle } from "react-icons/hi";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Pricing UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main > 
        <Box position='relative' height='100vh' bg='white'>

          <Box w='100%' height={['345px','400px']} bg='#6B46C1'>
            <Box pt={['40px','60px']} textAlign={['left', 'center']} px='25px'>
              <Heading color='#FFFFFF' > Simple pricing for your business </Heading>
              <Text color='#F7FAFC' pt={['12px', '20px']} fontWeight='400'>Plans that are carefully crafted to suit your business.</Text>
            </Box>
          </Box>
          <Box w='100%' position='absolute' top={['220px','250px']}  zIndex={10}>
            <Stack direction={['column','row']} alignItems='center' justifyContent='center' spacing={0}>
              <Box  boxShadow='xl' bg='#F0EAFB' textAlign='center' w={['365px','338px']} height={['283px','336px']} borderRadius={['12px 12px 0px 0px','12px 0px 0px 12px']}>
                <Heading color='#171923' fontSize='24px' fontWeight='800' pt={['40px', '50px']}>Premium PRO</Heading>
                <Heading color='#171923' fontSize={['48px','60px']} fontWeight='800' mt={['5px', '10px']}>$329</Heading>
                <Text color='#171923'  fontWeight='500'>billed just once</Text>
                <Button colorScheme='purple' w='282px' height='51px' mt={['30px','40px']}>Get Started</Button>
              </Box>
              <Box w={['365px','650px']} bg='#FFFFFF' height={['283px','336px']} boxShadow={['0px 4px 4px rgba(0, 0, 0, 0.25)','0px 20px 25px -5px rgba(0, 0, 0, 0.1), 0px 10px 10px -5px rgba(0, 0, 0, 0.04)']} padding={['30px 15px','30px 80px 30px 50px']} borderBottomRadius={['12px','0px']}>
                <Text color='#2D3748' fontSize={[18]} fontWeight='400'>Access these features when you get this pricing package for  your business.</Text>
                <Stack mt={[4,5]} color='#2D3748' spacing={5}  direction='column' fontSize={17}>
                  <HStack><Icon as={HiCheckCircle} color='#6134C4' boxSize={6}/><Text>International calling and messaging API</Text> </HStack>
                  <HStack><Icon as={HiCheckCircle} color='#6134C4' boxSize={6}/><Text>Additional phone numbers</Text> </HStack>
                  <HStack><Icon as={HiCheckCircle} color='#6134C4' boxSize={6}/><Text>Automated messages via Zapier</Text> </HStack>
                  <HStack><Icon as={HiCheckCircle} color='#6134C4' boxSize={6}/><Text>24/7 support and consulting</Text> </HStack>
                </Stack>
              </Box>
            </Stack>
            {/* <HStack><Icon as={HiCheckCircle} color='#6134C4' boxSize={6}/><Text>24/7 support and consulting</Text> </HStack> */}
          <Stack direction={['column','row']}  alignItems='center' justifyContent='center' fontWeight={700} fontSize={18} color='#171923' spacing={[8,20]} px={['20px','30px']} py={['30px','70px']} mb={[10,0]} >
             <HStack w={['100%',250]} spacing={6} alignItems='center'  justifyContent='start'>
              <Image src='/Group.svg' alt='group.png' w={[9,12]} h={[9,12]} />
              <Text>30 days money back
                 Guarantee</Text>
             </HStack>

             <HStack w={['100%',250]} spacing={6} alignItems='center'  justifyContent='start'>
              <Image src='/second.svg' alt='group.png' w={[9,12]} h={[9,12]} />
              <Text>No setup fees 100% hassle-free</Text>
             </HStack>

             <HStack w={['100%',300]} spacing={6} alignItems='center'  justifyContent='start'>
              <Image src='/arrow.svg' alt='group.png' w={[9,12]} h={[9,12]} />
              <Text>No monthly subscription Pay once and for all</Text>
             </HStack>

          </Stack>
          </Box>
        </Box>
      </main>
    </>
  )
}
